- hosts: pi
  become: true
  pre_tasks:
  - name: Update cache
    apt:
        update_cache: yes
        cache_valid_time: 3600

  - name: Update all packages to the latest version
    apt:
        upgrade: dist

  roles:
      - base
      #- bluetooth
      #- plex
      #- nfs
      # - nginx
      # - wlan
      # - dhcp
      # - proxy
      # - samba
      # - airsonic
      # - monit
      # - mail
      # - cacti
