- name: Install packages for bluetooth
  apt:
      pkg: [
          'pi-bluetooth',
          'bluez',
          'bluez-firmware',
          'blueman',
          'libbluetooth-dev'
      ]
      state: present
  notify:
      - restart bluetooth

- name: Install packages for pygattlib
  apt:
      pkg: [
          'libboost-python-dev',
          'libboost-thread-dev',
          'libglib2.0-dev',
          'libgtk2.0-dev',
          'libperl-dev'
      ]
      state: present

- name: Ensure bluetooth service is running
  service:
      name: bluetooth
      state: started
      enabled: yes
