- name: Install packages for bluetooth
  apt:
      pkg: "{{item}}"
      state: installed
  with_items:
      - pi-bluetooth
      - bluez
      - bluez-firmware
      - blueman
      - libbluetooth-dev

- name: Install packages for pygattlib
  apt:
      pkg: "{{item}}"
      state: installed
  with_items:
      - libboost-python-dev
      - libboost-thread-dev
      - libglib2.0-dev
      - libgtk2.0-dev
      - libperl-dev

- name: Ensure bluetooth service started
  service:
      name: bluetooth
      state: restarted
      enabled: yes
