- name: Install packages for NFS
  apt:
      pkg: "{{item}}"
      state: installed
  with_items:
      - nfs-kernel-server
      - nfs-common
      - portmap

- name: /etc/exportfs
  copy:
    src: ./roles/nfs/files/exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify:
       - reload exports
       - restart nfs-kernel-server
       - restart rpcbind

- name: Ensure nfs-kernel-server service is running
  service:
      name: nfs-kernel-server
      state: started
      enabled: yes

- name: Ensure rpcbind service is running
  service:
      name: rpcbind
      state: started
      enabled: yes

- name: Creates mount point directory
  file:
      path: /mnt/data
      state: directory

- name: Ensure fstab mount setting
  lineinfile:
      dest: /etc/fstab
      regexp: '^/dev/sda1'
      line: '/dev/sda1   /mnt/data   ext4   defaults,auto   0   3'
