- name: Install packages for NFS
  apt:
      pkg: "{{item}}"
      state: installed
  with_items:
      - nfs-kernel-server
      - nfs-common
      - portmap

- name: /etc/exportfs
  copy:
    src: ./roles/nfs/files/exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Ensure nfs-kernel-server service running
  service:
      name: nfs-kernel-server
      state: started
      enabled: yes

- name: Ensure rpcbind service running
  service:
      name: rpcbind
      state: started
      enabled: yes

- name: Run exportfs command
  command: exportfs -r
