- name: Install dnsmasq package
  apt:
      pkg: 'dnsmasq'
      state: present

- name: Ensure conf-dir setting uncomment
  lineinfile:
      dest: /etc/dnsmasq.conf
      regexp: '^#conf-dir=/etc/dnsmasq.d$'
      line: 'conf-dir=/etc/dnsmasq.d'
      firstmatch: yes
      state: present
      backrefs: yes
  notify:
       - restart dnsmasq

- name: Set /etc/dnsmasq.d/atsmin.conf
  copy:
      src: ./roles/dhcp/files/atsmin.conf
      dest: /etc/dnsmasq.d/atsmin.conf

- name: Ensure dnsmasq service is running
  service:
      name: dnsmasq
      state: started
      enabled: yes
