- name: Install apt packages
  apt:
      pkg: [
          'vim',
          'python-dev',
          'python3-pip',
          'python-pip',
          # 'rubygems',
          'libpq-dev',
          'libreadline-dev',
          'nodejs',
          # for mounting windows filesystem
          'ntfs-3g',
          # for allowing apt to use a repository over HTTPS
          'apt-transport-https',
          'ca-certificates',
          'curl',
          'gnupg2',
          'software-properties-common',
           # for datadog monitoring
          'sysstat',
          'libcurl4-openssl-dev',
          'fail2ban',
          'lvm2',
          'snmpd'
      ]
      state: present

- name: Check docker is already installed
  stat:
      path: /var/lib/docker
  register: path

- name: Install docker if not installed yet
  shell: curl -sSL https://get.docker.com | sh
  when: path.stat.isdir is not defined

- name: upgrade pip
  shell: pip install pip --upgrade

- name: disable swap
  shell: dphys-swapfile swapoff

- name: Install python packages
  pip:
      name: docker-py

- name: Set static ip address
  copy:
      src: ./roles/base/files/dhcpcd.conf
      dest: /etc/dhcpcd.conf
      owner: root
      group: netdev
      mode: 664

- name: Set /etc/motd
  copy:
      src: ./roles/base/files/motd
      dest: /etc/motd

- name: Install ntp
  apt:
      pkg: ntp
      state: present
  notify:
       - restart ntp

- name: Ensure ntp nict setting
  lineinfile:
      dest: /etc/ntp.conf
      regexp: 'ntp.nict.jp'
      line: 'pool ntp.nict.jp iburst'

- name: Ensure ntp service is running
  service:
      name: ntp
      state: started
      enabled: yes

- name: Ensure snmpd service is running
  service:
      name: snmpd
      state: started
      enabled: yes
