- name: Update cache
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install apt packages
  apt:
      pkg: "{{item}}"
      state: installed
  with_items:
      - python-dev
      - ntfs-3g  # for mounting windows filesystem

- name: Install python packages
  pip:
      name: docker-py

- name: Set /etc/motd
  file:
      src: ./roles/base/files/motd
      dest: /etc/motd
