- name: Creates library directory
  file:
      path: /mnt/data/library
      state: directory

- name: Plex media server container present
  docker_container:
      name: plex
      image: besn0847/arm-plex
      state: present
  tags:
      - plex

- name: Restart container
  docker_container:
      name: plex
      image: besn0847/arm-plex
      state: started
      restart: yes
      network_mode: host
      exposed_ports:
          - 32400
      volumes:
          - "/mnt/data/library:/data"
  tags:
      - plex
